compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fp16: false
machine_rank: 0
main_process_ip: 10.0.1.172
main_process_port: 21777
main_training_function: main
num_machines: 2
num_processes: 2
